version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: salaQR-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: reservas
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - salaQR-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: salaQR-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/?authSource=admin
      - PORT=4000
      - NODE_ENV=production
      - TZ=Europe/Madrid
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - salaQR-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: salaQR-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - salaQR-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongo-data:

networks:
  salaQR-network:
    driver: bridge
